# Uncomment the next line to define a global platform for your project
# platform :ios, '14.2'

target 'CEP' do

pod 'SwiftLint'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CEP

  target 'CEPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CEPUITests' do
    # Pods for testing
  end

end
